sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

env:
  - TEST_SUITE=travis_wait gradle check --stacktrace
  - TEST_SUITE=gradle fullAcceptanceTest --stacktrace

# run tests
script: "$TEST_SUITE"

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
