sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - sudo /etc/init.d/postgresql stop
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
#  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

env:
  - DOCKER_COMPOSE_VERSION=""
  - TEST_SUITE="travis_wait gradle check --stacktrace"   # unit tests
  - TEST_SUITE="gradle fullAcceptanceTest --stacktrace"  # acceptance tests

# run test suits in parallel
script: "$TEST_SUITE"

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

after_script:
  - docker-compose down