sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - pip install --user codecov

# run tests
script:
  - gradle check fullAcceptanceTest --stacktrace

after_success:
  - codecov