sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  

# run tests
script:
  - travis_wait gradle check --stacktrace
  - gradle fullAcceptanceTest --stacktrace

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
