sudo: required

language: python

services:
  - docker

python:
  - "3.4"

# build and run docker container with kafka
before_install:
  - make --directory local-test run

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - py.test nakadi/test
